import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import Image from 'next/image'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Reinhart-King Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
      <body className="bg-gray-100">
      <main>
      <div className="bg-gray-900 text-white text-left w-full py-2">
        <div className="grid grid-cols-2">
          <div className="flex flex-col px-6">
            <h1 className="text-5xl">Reinhart-King Laboratory</h1>
            <p className="flex flex-grow items-center text-xs">Multidisciplinary approaches to understanding cellular mechanics and cell-biomaterial interactions</p>
          </div>
          <div className="flex">
            <Image className="h-20 w-auto ml-auto px-2" src="/crk-logo.jpg" width={180} height={180} alt="crk logo"/>
          </div>
        </div>
      </div>
        <nav className="bg-gray-200 text-white w-full">
          <div className="max-w-16xl mx-auto px-2 sm:px-6 lg:px-8">
            <div className="relative flex items-center justify-between h-14">
              <div className="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
                <div className="flex space-x-2">
                  <Link href="/" className="text-gray-900 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" aria-current="page">Home</Link>
                  <Link href="/research" className="text-gray-900 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Research</Link>
                  <Link href="/people" className="text-gray-900 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">People</Link>
                  <Link href="/meetthepi" className="text-gray-900 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Meet the PI</Link>
                  <Link href="/news" className="text-gray-900 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">News</Link>
                  <Link href="/publications" className="text-gray-900 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Publications</Link>
                  <Link href="/defensecakes" className="text-gray-900 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Defense Cakes</Link>
                  <Link href="/contact" className="text-gray-900 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Contact</Link>
                  <Link href="/data" className="text-gray-900 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Data</Link>
                </div>
              </div>
            </div>
          </div>
        </nav>
      {children}
      </main>
      </body>
    </html>
  );
};